name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Changes directory
        run: |
          cd major_paper
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: major_paper.tex
